[phases.setup]
packages = [
    "php81.withExtensions (pe: [pe.curl, pe.mbstring, pe.xml, pe.pdo_mysql])", # Extensiones esenciales
    "nginx",
    "libmysqlclient",
    "php81Packages.composer",
    "nodejs_18"
]

[phases.install]
commands = [
    # Prepara directorios críticos primero
    "mkdir -p storage/framework/{cache,sessions,views}",
    "chmod -R 775 storage bootstrap/cache",
    
    # Instala dependencias
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci --production",
    "npm run build"
     "php artisan migrate --force"
]

[phases.start]
commands = [
    # Solo comandos de inicio (las migraciones se moverán a install)
    "php-fpm"
]
